import type Agent from "@tokenring-ai/agent/Agent";
import type { InputAttachment, OutputArtifactSchema, ToolCallResult } from "@tokenring-ai/agent/AgentEvents";
import { SubAgentConfigSchema } from "@tokenring-ai/agent/schema";

import type { Tool as AITool } from "@tokenring-ai/ai-client";
import type { AIResponse, ChatInputMessage, ChatRequest } from "@tokenring-ai/ai-client/client/AIChatClient";
import type { MaybePromise } from "bun";
import { z } from "zod";

const initialContextItems = [{ type: "system-message" }, { type: "tool-context" }, { type: "prior-messages" }, { type: "current-message" }];

const followUpContextItems = [{ type: "prior-messages" }, { type: "current-message" }];

export type ToolArtifact = Omit<z.input<typeof OutputArtifactSchema>, "type">;

export type NamedTool = {
  name: string;
  tool: AITool;
  toolDefinition?: TokenRingToolDefinition<any>;
};

export type TokenRingFullToolResult = Omit<ToolCallResult, "type" | "timestamp" | "summary" | "name" | "args"> & {
  summary?: string | undefined;
  type?: never;
  name?: never; // Generated by the tool call wrapper
  args?: never; // Generated by the tool call wrapper
  text?: never; // This should now be send back in the results.
  artifact?: never; // This should now be send back in the results.
};

export type TokenRingToolResult = string | TokenRingFullToolResult;

export type TokenRingToolDefinition<InputSchema extends AITool["inputSchema"]> = {
  /* The name of the tool, as seen by the model */
  name: string;
  /* The display name of the tool, as seen by the user */
  displayName: string;
  description: string;
  execute: (input: z.output<InputSchema>, agent: Agent) => MaybePromise<TokenRingToolResult>;
  inputSchema: InputSchema;
  start?: (agent: Agent) => Promise<void>;
  stop?: (agent: Agent) => Promise<void>;
  requiredContextHandlers?: string[] | undefined;
  adjustActivation?: (enabled: boolean, agent: Agent) => boolean | Promise<boolean>;
};

export const ContextSourceSchema = z.looseObject({
  type: z.string(),
});

export const ChatAgentConfigSchema = z
  .object({
    model: z.string().exactOptional(),
    systemPrompt: z.string(),
    maxSteps: z.number().exactOptional(),
    allowRemoteAttachments: z.boolean().exactOptional(),
    compaction: z
      .object({
        policy: z.enum(["automatic", "ask", "never"]).exactOptional(),
        compactionThreshold: z.number().exactOptional(),
        applyThreshold: z.number().exactOptional(),
        background: z.boolean().exactOptional(),
        focus: z.string().exactOptional(),
      })
      .prefault({}),
    enabledTools: z.array(z.string()).exactOptional(),
    hiddenTools: z.array(z.string()).exactOptional(),
    context: z
      .object({
        initial: z.array(ContextSourceSchema).default(initialContextItems),
        followUp: z.array(ContextSourceSchema).default(followUpContextItems),
      })
      .exactOptional(),
  })
  .strict();

const ChatAgentDefaultConfig = z
  .object({
    model: z.string().exactOptional(),
    enabledTools: z.array(z.string()).default([]),
    hiddenTools: z.array(z.string()).default([]),
    maxSteps: z.number().default(0),
    allowRemoteAttachments: z.boolean().default(true), //TODO: Evaluate security risks associated with this
    compaction: z
      .object({
        policy: z.enum(["automatic", "ask", "never"]).default("ask"),
        compactionThreshold: z.number().default(0.5),
        applyThreshold: z.number().exactOptional(),
        background: z.boolean().default(false),
        focus: z.string().default(
          `
- Important Details
- Resources, files, or URLs that were referenced
- A clear description of the current task
- A summary of the previous steps taken
- Key details about the current task
- Any other relevant information that might be useful for the current task
    `.trim(),
        ),
      })
      .prefault({}),
    context: z
      .object({
        initial: z.array(ContextSourceSchema).default(initialContextItems),
        followUp: z.array(ContextSourceSchema).default(followUpContextItems),
      })
      .prefault({}),
  })
  .strict();

export const ChatServiceConfigSchema = z.object({
  defaultModels: z.array(z.string()).default([]),
  agentDefaults: ChatAgentDefaultConfig.prefault({}),
});

export const ChatConfigMergedSchema = z.object({
  ...ChatAgentConfigSchema.shape,
  ...ChatAgentDefaultConfig.shape,
});

export const ChatToolInputArgumentSchema = z.object({
  description: z.string(),
  defaultValue: z.string().exactOptional(),
});

export const ChatToolConfigSchema = z.object({
  /** Type of agent used to execute the tool */
  agentType: z.string(),
  /** Tool Display Name */
  displayName: z.string(),
  /** Tool Description */
  description: z.string(),
  /** Tool Input Schema */
  inputArguments: z.record(z.string(), ChatToolInputArgumentSchema),
  /** The steps to execute */
  steps: z.array(z.string()).min(1),
  /** The subagent configuration */
  subAgent: SubAgentConfigSchema.prefault({}),
});
export type ChatToolConfig = z.infer<typeof ChatToolConfigSchema>;

export type ChatAgentConfig = {
  chat: z.input<typeof ChatAgentConfigSchema>;
};

export type ParsedChatConfig = z.output<typeof ChatConfigMergedSchema>;
export type ContextItem = ChatInputMessage;

export type ContextHandlerOptions = {
  input: string;
  attachments?: InputAttachment[];
  chatConfig: ParsedChatConfig;
  sourceConfig: z.infer<typeof ContextSourceSchema>;
  agent: Agent;
};
export type ContextHandler = (options: ContextHandlerOptions) => AsyncGenerator<ContextItem> | Generator<ContextItem>;
/**
 * Represents a chat message in the storage system
 */
export type StoredChatMessage = {
  /** The AI request */
  request: Omit<ChatRequest, "tools"> & { tools?: never };
  /** The response from AI */
  response: AIResponse;
  /** The creation time in milliseconds since the epoch format */
  createdAt: number;
  /** The update time in milliseconds since the epoch format */
  updatedAt: number;
};

export const StoredChatCompactionSchema = z.object({
  startIndex: z.number().int().nonnegative(),
  endIndex: z.number().int().nonnegative(),
  messages: z.array(z.any()),
  createdAt: z.number(),
});

export type StoredChatCompaction = {
  startIndex: number;
  endIndex: number;
  messages: ChatInputMessage[];
  createdAt: number;
};
